"""First-use bootstrap: writes the `code-intelligence` Claude Code skill.

Called from `Workspace.index()` the first time a workspace has no
`.code-intelligence/` state directory yet (detected in `Workspace.open()`,
right after that first successful `index()` call completes). Two branches:

- **dotfiles itself** (detected via the presence of
  `scripts/dev/sync_cross_project_skills.sh` at the workspace root): a
  **documented no-op** in Phase A. dotfiles has its own three-location
  skill-sync system (`.claude/commands/`, `.github/skills/`,
  `stow/config/.config/opencode/skills/`) and retiring the old
  `code-quality` skill / authoring a new `code-intelligence` one through
  that system is explicitly Phase B's job (it happens together with the
  `tools/code_quality/` deletion, per the plan's Migration section) — this
  function only *logs* what it would do and returns, never writing into
  `.claude/skills/` inside dotfiles.
- **any other workspace**: writes/overwrites
  `.claude/skills/code-intelligence/SKILL.md` (creating `.claude/skills/`
  if needed) — a plain frontmatter (`name`, `description`) + Markdown body
  explaining the CLI and the query-before-you-read workflow. Deterministic
  and idempotent: the same tool version always regenerates byte-identical
  output. Also ensures `.code-intelligence/` is listed in that workspace's
  `.gitignore`.
"""

from pathlib import Path

from code_intelligence import __version__
from code_intelligence.core.workspace.allowlist import authorize

#: The file whose presence marks a workspace as *this* repository
#: (dotfiles), which uses its own skill-sync system instead of the generic
#: per-workspace `.claude/skills/` path.
_DOTFILES_MARKER = "scripts/dev/sync_cross_project_skills.sh"

_SKILL_MD_TEMPLATE = """\
---
name: code-intelligence
description: {description}
---

<!--
  Auto-generated by code-intelligence {version} on first use of this
  workspace. Safe to regenerate — running `code-intelligence index` again
  on a workspace whose `.claude/skills/code-intelligence/SKILL.md` is
  missing (or was deleted) recreates this file with identical content for
  the same tool version. Do not hand-edit; edit the generator instead:
  `code_intelligence/bootstrap/skill_writer.py`.
-->

# Code Intelligence

This workspace is indexed by **code-intelligence**, a persistent,
incremental, symbol-oriented index. Query it instead of opening whole
files — most questions ("where is X defined", "what does this function's \
body look like", "what breaks quality rules here") are answered by a small,
precise query, not a full-file read.

## Prefer the MCP server when it's configured

If tools named `mcp__code_intelligence__*` are available, use them
directly instead of the CLI below — one structured JSON call, no
subprocess, and a strictly larger surface (build/test/lint/format
orchestration, git status/log/blame/diff, gated multi-site rename — none
of which the CLI has yet):

- `find_symbol` / `search_text` / `list_symbols` — resolve/search/enumerate symbols; every text hit is tagged with its enclosing symbol.
- `get_source_range` / `symbol_source` / `outline_symbol` — exact, budget-checked source. An oversized request returns `{{"truncated": true, "recommended_ranges": [...]}}` instead of a silent clip — read what it recommends, never guess a smaller range yourself.
- `find_references` / `find_dependencies` — L6 callers/callees. Every row is marked `"exact"` (a real compiler resolved it) or `"heuristic"` (name-matching only) — never read a heuristic "0 callers" as dead code.
- `get_violations` / `summarize_violations` / `rank_symbols` — structural findings (naming, missing docs, LOC/complexity, duplication) and complexity hotspots.
- `rename_symbol` — rename a definition and every exact-backend call site in one gated operation (`dry_run=True` first; refuses without exact semantic coverage rather than guessing).
- `workspace_index` — re-index after changing code (incremental; only changed files reparse).
- `compare_baseline` — diff against `HEAD`, `HEAD~1`, `working-tree`, `staged`, a branch, or a commit without a full re-scan.
- `run_build` / `run_tests` / `run_lint` / `run_format` / `detect_toolchain` — structured build/test/lint/format results (`status`, `counts`, `failed_tests`, a capped `log_tail`) instead of a raw log to re-parse by hand. `run_lint`/`run_format` currently cover Python (`ruff`) only.
- `git_status` / `git_log` / `git_blame` / `git_diff_stat` — repository state, commit history, per-line blame, and insertion/deletion counts without shelling out to `git` and re-parsing its human-oriented output.

## CLI fallback (no MCP configured)

The tool itself lives outside this workspace, at `{cq_root}`. Invoke it as:

```bash
CQ_PY="{cq_python}"
CQ_SCRIPT="{cq_script}"
test -x "$CQ_PY" || echo "code-intelligence not found at {cq_root} on this machine — skip these checks, don't reimplement or vendor a copy without asking first"
```

Every command below is `$CQ_PY $CQ_SCRIPT <subcommand> ...`, run from this
workspace's root. The CLI covers the query/violations/index/diff workflow
below only — build/test/lint/format orchestration, git status/log/blame,
and rename are MCP-only for now.

## Query-before-you-read workflow (CLI)

1. **Structure first, content last.** Start at the cheapest level that
   answers your question:
   - `$CQ_PY $CQ_SCRIPT query <path>` — per-file summary across the whole
     workspace (files, languages, symbol/violation counts).
   - `$CQ_PY $CQ_SCRIPT query <path> --file <relpath>` — every symbol in
     one file (kind, name, location, LOC, complexity) — no source text.
   - `$CQ_PY $CQ_SCRIPT symbol <symbol_id-or-name> [--file <relpath>]` —
     one symbol's full metadata (calls, called-by, violations) — still no
     source text.
   - `$CQ_PY $CQ_SCRIPT context <symbol_id> [--max-lines N]` — the
     symbol's actual source, budgeted. If it would exceed the budget you
     get `{{"truncated": true, "available_range": ..., "recommended_ranges": [...]}}`
     instead of a silently clipped body — never guess at a smaller range
     yourself, read what it recommends.
   - `$CQ_PY $CQ_SCRIPT range <path>:<start>-<end>` — an exact line range
     when you already know precisely what you need.
2. **Check violations before editing.** `$CQ_PY $CQ_SCRIPT violations
   [--severity SEV]` lists structural findings (naming, missing docs,
   multiple types per file, procedural monoliths, duplication, LOC/
   function-length thresholds) with `symbol_id`/location — narrower and
   cheaper than reading a file to spot problems yourself.
3. **Re-index after you change code.** `$CQ_PY $CQ_SCRIPT index` is
   incremental (only changed files reparse); run it again before your next
   query so results reflect your edits.
4. **Comparing against a point in history?** `$CQ_PY $CQ_SCRIPT diff
   <ref>` (`HEAD`, `HEAD~1`, `working-tree`, `staged`, a branch, a commit)
   reports `added_symbols`/`removed_symbols`/`changed_symbols`/
   `changed_files`/`new_violations`/`resolved_violations`/`regressions`
   without a full re-scan.

## Notes

- `.code-intelligence/` (the SQLite index + this bootstrap marker) is
  workspace-local state, not meant to be committed — it's added to
  `.gitignore` automatically.
- Every finding and every symbol can carry a `confidence` field
  (`"high"`/`"medium"`/`"low"`) — a heuristic (e.g. cross-file duplication
  similarity) is never presented as certainty.
"""

_SKILL_DESCRIPTION = (
    "Query this workspace's persistent code-intelligence index (symbols, structure, "
    "violations, dependencies) instead of reading whole files."
)


def _render_skill_md() -> str:
    """Render the skill file's full content — deterministic for a given tool version and install path."""
    package_root = Path(__file__).resolve().parent.parent
    cq_python = package_root / ".venv" / "bin" / "python"
    cq_script = package_root / "code-intelligence.py"
    return _SKILL_MD_TEMPLATE.format(
        description=_SKILL_DESCRIPTION,
        version=__version__,
        cq_root=package_root,
        cq_python=cq_python,
        cq_script=cq_script,
    )


def is_dotfiles_workspace(root: Path) -> bool:
    """Return True when `root` is this repository (dotfiles), not a generic workspace."""
    return (root / _DOTFILES_MARKER).is_file()


def _ensure_gitignore_entry(root: Path) -> None:
    """Add `.code-intelligence/` to `root`'s `.gitignore` if it isn't already listed."""
    gitignore_path = root / ".gitignore"
    entry = ".code-intelligence/"
    existing = gitignore_path.read_text(encoding="utf-8") if gitignore_path.is_file() else ""
    if entry in existing.splitlines():
        return
    separator = "" if not existing or existing.endswith("\n") else "\n"
    gitignore_path.write_text(f"{existing}{separator}{entry}\n", encoding="utf-8")


def _write_generic_skill(root: Path) -> Path:
    """Write/overwrite `.claude/skills/code-intelligence/SKILL.md`; return its path."""
    skill_dir = root / ".claude" / "skills" / "code-intelligence"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text(_render_skill_md(), encoding="utf-8")
    _ensure_gitignore_entry(root)
    return skill_path


def bootstrap_workspace(root: Path) -> dict[str, object]:
    """Run the first-use bootstrap for `root`; returns a small report dict for logging/tests.

    Idempotent: calling this again produces byte-identical output for the
    same code-intelligence version (verified by
    `tests/test_bootstrap.py`'s two-run comparison).

    Also authorizes `root` on the daemon's allowlist (fixme §37) — first
    successful bootstrap *is* the authorization event, regardless of which
    branch below fires.
    """
    if is_dotfiles_workspace(root):
        # Made real in Phase B migration step 6e, once 1-5 are built/tested and the
        # actual `tools/code_quality/` retirement has happened — see
        # `bootstrap/dotfiles_sync.py` (added at that point) for the real
        # implementation. Until then this stays the Phase A documented no-op.
        if _dotfiles_sync_available():
            from code_intelligence.bootstrap.dotfiles_sync import sync_dotfiles_skill

            result = sync_dotfiles_skill(root)
        else:
            result = {
                "workspace": "dotfiles",
                "action": "no-op",
                "would_have_run": "scripts/dev/sync_cross_project_skills.sh (Phase B)",
            }
    else:
        skill_path = _write_generic_skill(root)
        result = {"workspace": "generic", "action": "wrote_skill", "path": str(skill_path)}
    authorize(root)
    return result


def _dotfiles_sync_available() -> bool:
    """True once `bootstrap/dotfiles_sync.py` exists (added by migration step 6e)."""
    return (Path(__file__).resolve().parent / "dotfiles_sync.py").is_file()


__all__ = ["bootstrap_workspace", "is_dotfiles_workspace"]
